### ISSUE TITLE
Type of thickness vector/map

### ISSUE THREAD

**Issue by JakobThumm** [Sven-Schepp/SaRA#1]
Hi Sven,

in https://github.com/Sven-Schepp/SaRA/blob/97c059b82297c67a1831fcbe43bc568e5a2f8ec1/ReachLib/include/articulated_pos.hpp#L58 we have to pass the thickness as a vector and in https://github.com/Sven-Schepp/SaRA/blob/97c059b82297c67a1831fcbe43bc568e5a2f8ec1/ReachLib/include/articulated_vel.hpp#L56 / https://github.com/Sven-Schepp/SaRA/blob/97c059b82297c67a1831fcbe43bc568e5a2f8ec1/ReachLib/include/articulated_accel.hpp#L56 as a map.

Is there a reason for the difference?

Should we pass `length`, `max_v`, and `max_a` in the same way as thickness?

**Comment by Sven-Schepp** [comment]
The implementation in G_POS seems like an oversight to me (legacy error). std::map carries the destinct advantage that an object can be identified by name while std::vector needs to be filled in a certain order increasing human error potential during definition. If possible, all body part related parameters should be passed as maps relating them to a specific body part instance with that name.

**Comment by JakobThumm** [comment]
> all body part related parameters should be passed as maps relating them to a specific body part instance with that name

Should I add this to https://github.com/Sven-Schepp/SaRA/pull/4 ?

**Comment by Sven-Schepp** [comment]
Yes, that seems sensible.

**Comment by Sven-Schepp** [comment]
This might lead to problems in reachable_occupancy (ROS) because of the example G_POS definitions there.

**Comment by Sven-Schepp** [comment]
> Yes, that seems sensible.
I have accidentaly merged https://github.com/Sven-Schepp/SaRA/pull/4 into SaRA. But it seems like this might be a bigger update that requires its own preq.

**Comment by JakobThumm** [comment]
> I have accidentaly merged https://github.com/Sven-Schepp/SaRA/pull/4 into SaRA. But it seems like this might be a bigger update that requires its own preq.

The PR itself doesn't break ReachLib. `reachable_occupancy` needs changes though.
