### ISSUE TITLE
Incorrect incorporation of Delay in BodyPartVel

### ISSUE THREAD

**Issue by JakobThumm** [Sven-Schepp/SaRA#8]
https://github.com/Sven-Schepp/SaRA/blob/4042d8a31c3d8e3c223dd72956ab723b6b9e98d8/ReachLib/src/body_part_vel.cpp#L102

The velocity should be multiplied with (t_b + delay).

**Comment by Sven-Schepp** [comment]
The error should be fixed in f021db9.

**Comment by JakobThumm** [comment]
Thank you :+1: 
I was planning to do a MR myself in the next days, but it's excellent that you already did it.
