### ISSUE TITLE
Inconsistencies in thickness

### ISSUE THREAD

**Issue by JakobThumm** [Sven-Schepp/SaRA#9]
There are two issues with the thickness of body parts / extremities.

1. The getter function of the body part misses an 's' https://github.com/Sven-Schepp/SaRA/blob/f021db97d1c8724bf4101000bbf61d44c89c56d4/ReachLib/include/body_part.hpp#L60
2. The thickness intuitively describes the diameter and not the radius. I would either rename thickness to radius or change the calculations in the update function to `r=thickness_/2 + ...`.

**Comment by Sven-Schepp** [comment]
Version dbceda9 addresses the issues as follows. The getter function was renamed to get_thickness(). The thickness parameter is now defined as the diameter of a body part (as you suggested -> `r = thickness/2.0`). This is documented within comments where needed.

**Comment by JakobThumm** [comment]
Sounds good. Thank you.
